phases:
  main:
    batch_size:
      train: 16
      validation: 16
    epochs: 90
    learning_rates:
      params: 0.1
    scheduler:
      _target_: torch.optim.lr_scheduler.StepLR
      _partial_: true
      step_size: 30
      gamma: 0.8