phases:
  main:
    batch_size:
      train: 64
      validation: 64
    epochs: 50
    learning_rates:
      params: 0.003
    optimizer:
      _target_: torch.optim.Adam
    scheduler:
      _target_: torch.optim.lr_scheduler.StepLR
      step_size: 25
      gamma: 0.8

params:
  _target_: xai_mam.models.BagNet.config.BagNetParameters
  loss:
    _target_: xai_mam.models.BagNet.config.BagNetLoss
    binary_cross_entropy: false
    coefficients:
      cross_entropy: 1.0