phases:
  main:
    batch_size:
      train: 32
      validation: 32
    epochs: 120
    learning_rates:
      params: 0.003
    scheduler:
      _target_: torch.optim.lr_scheduler.StepLR
      step_size: 30
      gamma: 0.8

params:
  _target_: xai_mam.models.BagNet.config.BagNetParameters
  loss:
    _target_: xai_mam.models.BagNet.config.BagNetLoss
    binary_cross_entropy: false
    coefficients:
      cross_entropy: 1.0