defaults:
  - _model_config
  - network: resnet18

name: protopnet

params:
  construct_trainer:
    _target_: ProtoPNet.models.ProtoPNet.construct_trainer
    _partial_: true
  prototypes:
    _target_: ProtoPNet.models.ProtoPNet.config.PrototypeProperties
    per_class: 10
    size: 256
    activation_fn: log  # log | linear | relu | sigmoid | tanh

network:
  _target_: ProtoPNet.models.ProtoPNet.config.ProtoPNetBackboneNetwork
  add_on_layer_properties:
    _target_: ProtoPNet.models.ProtoPNet.config.AddOnLayerProperties
    type: bottleneck  # regular | bottleneck
    activation: A     # A | B