defaults:
  - _config_validation  # type verification defined in config_types.py
  - _hydra_config
  - _self_
  - data/set: MIAS
  - data/filters: default
  - cross_validation: stratified
  - model: protopnet

hydra:
  run:
    dir: ${run_location:}/${model.name}/${now:%Y-%m-%d-%H-%M-%S}/${is_debug_mode:${data.datamodule.debug}}${data.set.name}-${is_backbone_only:${model.backbone_only}}${model.network.name}-${data.set.state}-${data.set.target.name}/${sanitize_override_dirname:${hydra:job.override_dirname}}
  sweep:
    subdir: ${model.name}/${now:%Y-%m-%d-%H-%M-%S}/${is_debug_mode:${data.datamodule.debug}}${data.set.name}-${is_backbone_only:${model.backbone_only}}${model.network.name}-${data.set.state}-${data.set.target.name}/${sanitize_override_dirname:${hydra:job.override_dirname}}
  job:
    config:
      override_dirname:
        exclude_keys:
          - data.datamodule.debug
          - data/set
          - data/set/state
          - data/set/target
          - model
          - model/network
          - model/backbone_only@model
  job_logging:
    root:
      level: INFO

data:
  datamodule:
    _target_: xai_mam.dataset.dataloaders.CustomDataModule
    _convert_: object  # Structured Configs are converted to instances
    data: ${data.set}
    classification: ${data.set.target.name}
    data_filters: ${data.filters}
    cross_validation_folds: ${cross_validation.folds}
    stratified: ${cross_validation.stratified}
    balanced: ${cross_validation.balanced}
    grouped: ${cross_validation.grouped}
    num_workers: ${job.number_of_workers}
    seed: ${seed}
    debug: false

seed: 42

job:
  number_of_workers: 4

outputs:
  dirs:
    checkpoints: checkpoints
    image: img
    metadata: metadata
    tensorboard: tensorboard
  file_prefixes:
    prototype: prototype-img
    self_activation: prototype-self-act
    bounding_box: prototype-bb
