defaults:
  - _config_validation  # type verification defined in config_types.py
  - _hydra_config
  - _self_
  - data/set: MIAS
  - data/filters: default
  - cross_validation: stratified
  - model: protopnet
  - data/augmentation@data.set.image_properties.augmentations.train: none
  - data/augmentation@data.set.image_properties.augmentations.validation: none

data:
  datamodule:
    _target_: xai_mam.dataset.dataloaders.CustomDataModule
    _convert_: object  # Structured Configs are converted to instances
    data: ${data.set}
    classification: ${data.set.target.name}
    data_filters: ${data.filters}
    cross_validation_folds: ${cross_validation.folds}
    stratified: ${cross_validation.stratified}
    balanced: ${cross_validation.balanced}
    grouped: ${cross_validation.grouped}
    n_workers: ${job.n_workers}
    seed: ${seed}
    debug: false
    batch_size:
      train: 128
      validation: 128

seed: 42

job:
  n_workers: 4

outputs:
  dirs:
    checkpoints: checkpoints
    image: img
    metadata: metadata
    tensorboard: tensorboard
  file_prefixes:
    prototype: prototype-img
    self_activation: prototype-self-act
    bounding_box: prototype-bb

hydra:
  run:
    dir: "${run_location:}/${model.name}/${now:%Y-%m-%d}/\
       ${is_debug_mode:${data.datamodule.debug}}${data.set.name}-\
       ${is_backbone_only:${model.backbone_only}}${model.network.name}-\
       ${data.set.state}-${data.set.target.name}/\
       ${data.set.image_properties.height}-${data.set.image_properties.width}-\
       ${sanitize_override_dirname:${hydra:job.override_dirname}}/\
       ${now:%H-%M-%S}"
  sweep:
    subdir: "${model.name}/${now:%Y-%m-%d}/\
      ${is_debug_mode:${data.datamodule.debug}}${data.set.name}-\
      ${is_backbone_only:${model.backbone_only}}${model.network.name}-\
      ${data.set.state}-${data.set.target.name}/\
      ${data.set.image_properties.height}-${data.set.image_properties.width}-\
      ${sanitize_override_dirname:${hydra:job.override_dirname}}/\
      ${now:%H-%M-%S}"
  job:
    config:
      override_dirname:
        exclude_keys:
          - gpu.device_ids
          - data.datamodule.debug
          - data/set
          - data/set/state
          - data/set/target
          - data.set.image_properties.height
          - data.set.image_properties.width
          - model
          - model/network
          - model/backbone_only
  job_logging:
    root:
      level: INFO