defaults:
  - _config_validation  # type verification defined in xai_mam/scripts/datasets/convert_png_to_npz.py
  - _hydra_config
  - _self_
  - data/set: MIAS

hydra:
  run:
    dir: ${run_location:}/${data.set.name}/${data.set.state}
  sweep:
    subdir: ${data.set.name}/${data.set.state}
