defaults:
  - _config_validation  # type verification defined in xai_mam/scripts/datasets/define_mean_and_std.py
  - _hydra_config
  - _self_
  - data/set: MIAS

hydra:
  run:
    dir: ${run_location:}/${data.set.name}/${data.set.state}
  sweep:
    subdir: ${data.set.name}/${data.set.state}

dataset:
  _target_: xai_mam.dataset.dataloaders.CustomVisionDataset
  dataset_meta: ${data.set}
  classification: ${data.set.target.name}
  subset: all
  normalize: false
