defaults:
  - _config_validation  # type verification defined in xai_mam/scripts/datasets/define_mean_and_std.py
  - _hydra_config
  - _self_
  - data/set: MIAS
  - data/augmentation@augmentations.train: repeated_shape_33

dataset:
  _target_: xai_mam.dataset.dataloaders.CustomVisionDataset
  dataset_meta: ${data.set}
  classification: ${data.set.target.name}
  subset: train
  normalize: false

output_dir: "all-repeated_shape_33"

hydra:
  run:
    dir: ${run_location:}/${data.set.name}/${data.set.state}
  sweep:
    subdir: ${data.set.name}/${data.set.state}
