defaults:
  - _hydra_config
  - _config_validation  # type verification defined in xai_mam/scripts/test_models/train_torchvision_resnet_on_CIFAR.py
  - _self_

epochs: 60
batch_size: 128
model_name: resnet18
learning_rate: 0.01

hydra:
  run:
    dir: ${run_location:}/${hydra.job.override_dirname}/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    subdir: ${hydra.job.override_dirname}/${now:%Y-%m-%d-%H-%M-%S}