defaults:
  - _network_validation  # type verification defined in config_types.py

pretrained: true

backbone_only: false

add_on_layer_properties:
  type: bottleneck  # regular | bottleneck
  activation: A     # A | B