hydra:
  run:
    dir: runs/${hydra.job.name}/${data.set.name}-${network.name}-${data.set.state}-${target}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: runs/${hydra.job.name}
    subdir: ${data.set.name}-${network.name}-${data.set.state}-${target}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: conf
  job_logging:
    formatters:
      simple:
        format: '[%(asctime)s %(levelname)s] %(message)s'
