defaults:
  - _config_validation  # type verification defined in config_types.py
  - _hydra_config
  - _self_
  - data/set: MIAS
  - data/filters: default
  - cross_validation: stratified
  - network: resnet18

hydra:
  run:
    dir: ${oc.env:PROJECT_ROOT}/runs/${hydra.job.name}/${data.set.name}-${format_backbone_only:${network.backbone_only}}${network.name}-${data.set.state}-${data.set.target.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    subdir: ${data.set.name}-${network.name}-${data.set.state}-${format_backbone_only:${network.backbone_only}}${data.set.target.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

data:
  datamodule:
    _target_: ProtoPNet.dataset.dataloaders.CustomDataModule
    data: ${data.set}
    classification: ${data.set.target.name}
    data_filters: ${data.filters}
    cross_validation_folds: ${cross_validation.folds}
    stratified: ${cross_validation.stratified}
    balanced: ${cross_validation.balanced}
    grouped: ${cross_validation.grouped}
    num_workers: ${job.number_of_workers}
    seed: ${seed}
    debug: true

seed: 42

prototypes:
  per_class: 10
  size: 256
  activation_fn: log  # log | linear | relu | sigmoid | tanh

phases:
  warm:
    batch_size: 32
    epochs: 4
    learning_rates:
      add_on_layers: 3e-3
      prototype_vectors: 3e-3
    weight_decay: 1e-3
  joint:
    batch_size: 8
    epochs: 10
    learning_rates:
      features: 1e-4
      add_on_layers: 3e-3
      prototype_vectors: 3e-3
    scheduler:
      _target_: torch.optim.lr_scheduler.StepLR
      _partial_: true
      step_size: 5
      gamma: 0.1
  push:
    batch_size: 16
    start: 2
    interval: 5
  finetune:
    batch_size: 32
    epochs: 4
    learning_rates:
      features: 1e-4

loss:
  binary_cross_entropy: false
  separation_type: avg  # avg | max | margin
  coefficients:
    cross_entropy: 1.0
    clustering: 8e-1
    separation: 6e-1
    separation_margin: 0
    l1: 1e-4
    l2: 1e-2

job:
  number_of_workers: 4

outputs:
  dirs:
    model: model
    image: img
  file_prefixes:
    prototype: prototype-img
    self_activation: prototype-self-act
    bounding_box: prototype-bb
