defaults:
  - _config_validation  # type verification defined in config_types.py
  - _self_
  - data/set: MIAS
  - data/filters: default
  - cross_validation: stratified
  - network: resnet18

target: normal_vs_abnormal  # normal_vs_abnormal | benign_vs_malignant | normal_vs_benign_vs_malignant

data:
  dataloader:
    _target_: ProtoPNet.dataset.dataloaders.CustomDataModule
    data: ${data.set}
    classification: ${target}
    data_filters: ${data.filters}
    cross_validation_folds: ${cross_validation.folds}
    stratified: ${cross_validation.stratified}
    balanced: ${cross_validation.balanced}
    groups: ${cross_validation.grouped}
    num_workers: ${job.number_of_workers}
    seed: ${seed}

log_dir: ${oc.env:PROJECT_ROOT}/runs/default

seed: 42

gpu_ids:
  - 1

prototypes:
  per_class: 10
  size: 256
  activation_fn: log  # log | linear | relu | sigmoid | tanh

phases:
  warm:
    batch_size: 32
    epochs: 4
    learning_rates:
      add_on_layer: 3e-3
      prototype_vectors: 3e-3
    weight_decay: 1e-3
  joint:
    batch_size: 8
    epochs: 10
    learning_rates:
      feature: 1e-4
      add_on_layer: 3e-3
      prototype_vectors: 3e-3
    step_size: 5
  push:
    batch_size: 16
    start: 2
    interval: 5
  finetune:
    epochs: 4
    learning_rates:
      feature: 1e-4

loss:
  binary_cross_entropy: false
  separation_type: avg  # avg | max | margin
  coefficients:
    cross_entropy: 1.0
    clustering: 8e-1
    separation: 6e-1
    separation_margin: 0
    l1: 1e-4
    l2: 1e-2

job:
  number_of_workers: 4
