defaults:
  - _hydra_config
  - _self_
  - data/set: MIAS

hydra:
  run:
    dir: ${oc.env:RUNS_DIR}/${hydra.job.name}/${data.set.name}/${data.set.state}
  sweep:
    subdir: ${data.set.name}/${data.set.state}

dataset:
  _target_: ProtoPNet.dataset.dataloaders.CustomVisionDataset
  dataset_meta: ${data.set}
  classification: ${data.set.target.name}
  subset: all
  normalize: false
