phases:
  joint:
    batch_size:
      train: 16
      validation: 8
    epochs: 10
    learning_rates:
      features: 1e-4
      add_on_layers: 3e-3
      prototype_vectors: 3e-3
    scheduler:
      _target_: torch.optim.lr_scheduler.StepLR
      _partial_: true
      step_size: 5
      gamma: 0.1

params:
  _target_: xai_mam.models.ProtoPNet.config.backbone.ProtoPNetBackboneParameters
  loss:
    _target_: xai_mam.models.ProtoPNet.config.ProtoPNetLoss
    binary_cross_entropy: false
    coefficients:
      cross_entropy: 1.0
      l1: 1e-4