phases:
  warm:
    batch_size:
      train: 256
      validation: 128
    epochs: 4
    learning_rates:
      add_on_layers: 3e-3
      prototype_vectors: 3e-3
    optimizer:
      _target_: torch.optim.Adam
    weight_decay: 1e-3
  joint:
    batch_size:
      train: 256
      validation: 128
    epochs: 10
    learning_rates:
      features: 1e-4
      add_on_layers: 3e-3
      prototype_vectors: 3e-3
    optimizer:
      _target_: torch.optim.Adam
    scheduler:
      _target_: torch.optim.lr_scheduler.StepLR
      step_size: 5
      gamma: 0.1
  finetune:
    batch_size:
      train: 256
      validation: 128
    epochs: 4
    learning_rates:
      classification: 1e-4
    optimizer:
      _target_: torch.optim.Adam

params:
  _target_: xai_mam.models.ProtoPNet.config.explainable.ProtoPNetExplainableParameters
  push:
    _target_: xai_mam.models.ProtoPNet.config.explainable.PushSettings
    batch_size: 128
    start: 2
    interval: 5
  class_specific: true
  loss:
    _target_: xai_mam.models.ProtoPNet.config.explainable.ProtoPNetExplainableLoss
    binary_cross_entropy: false
    separation_type: avg  # avg | max | margin
    coefficients:
      cross_entropy: 1.0
      clustering: 8e-1
      separation: -8e-2
      separation_margin: 0
      l1: 1e-4
      l2: 1e-2