defaults:
  - _model_config
  - network: resnet18

name: protopnet
log_parameters_fn: xai_mam.models.xai_mam.log_parameters

params:
  construct_trainer:
    _target_: xai_mam.models.xai_mam.construct_trainer
    _partial_: true
  prototypes:
    _target_: xai_mam.models.xai_mam.config.PrototypeProperties
    per_class: 10
    size: 256
    activation_fn: log  # log | linear | relu | sigmoid | tanh

network:
  _target_: xai_mam.models.xai_mam.config.ProtoPNetBackboneNetwork
  add_on_layer_properties:
    _target_: xai_mam.models.xai_mam.config.AddOnLayerProperties
    type: bottleneck  # regular | bottleneck
    activation: A     # A | B